### ISSUE TITLE
Amount of logins leads to blocking account

### ISSUE THREAD

**Issue by woopstar** [audiconnect/audi_connect_ha#213]
On a Danish Facebook group, this notice was posted today.  It means we need to take into consideration the amount of polling when using the plugin, especially if you have more things that talk to MyAudi like apps and such.

What the number is, I don't know. Just posting it for reference.

![image](https://github.com/arjenvrh/audi_connect_ha/assets/2997782/4526ee66-fca2-4e59-aed7-7beca64f138d)

**Comment by Gunth** [comment]
I also had the same email from the audi support.

**Comment by jocxfin** [comment]
Seems to be that the HA is using this user agent: 

`class AudiAPI:
    HDR_XAPP_VERSION = "4.16.0"
    HDR_USER_AGENT = "myAudi-Android/4.13.0 (Build 800238275.2210271555) Android/11"
`

I'm right now decompiling the latest version to see if they have made changes. Bare with me

**Comment by slot-tronic** [comment]
Hi all, 

Just wanted to post here my discoveries of the last weeks. To me it seems we will not be able to use remote access via AudiConnect in the future except via the official Audi app. I am living in Germany and also use AudiConnect, plus a electricity provider integration for smart charging (Tibber Audi plugin) and the HomeAssistant integration for an etron S.

I see two serious issues coming to us:
First, I see today a completely inacceptable low number of requests per day possible at all: Even after deactivation of Tibber plugin and HomeAssistant integration, I cannot reach the car via AudiConnect app in the afternoon (I use it to remote start the heater 20 minutes before driving home from work)

Second, Audi even seems to plan to completely deactivate 3rd party access to the AudiConnect services and exclusively support remote access via their app. In my MyAudi account, I get the following bad news (sorry for the German, but this is my UI language):

![image](https://github.com/arjenvrh/audi_connect_ha/assets/48852836/0b2250a6-8569-4881-bd81-4db9168799ab)

If this is where Audi is heading, it will not help to keep or win back customers from more innovative OEMs at all. I sent a detailed explanation of my use-cases and a complaint to keep the services available to them by mail, now curious for their answer. (And I even guess the same is valid for all VW group brands since they for sure use the same backend). I will order a new car in the next months and if I don't receive an acceptable answer, I will definitely not take a VW brand car then. Can only recommend to you guys to do the same (If you want to spend the effort).

CU, Steffen

**Comment by slot-tronic** [comment]
Hi derhappy,

I completely agree with what you write Audi will do. Since I work in automotive electronic engineering (and it seems you maybe also know what's going on in the business ;-)), still I took the effort to write to them that I believe they should open up more to such things.

E.g., beyond the AudiConnect integration for HA, I use Tibber as electricity provider with variable pricing here in Germany, and they have an AudiConnect connection to support smart charging at the benefit of our grid and my money. This also does not work any more and gives constant error messages. I wrote to the Audi guys that my next car decision (happening in May 2024) will clearly depend on how they deal with my request to keep fill support for 3rd party service providers, specifically HA and Tibber, to use AudiConnect. 

Tibber for example also supports the following car brands today: Tesla, BMW, Nio, Polestar, Volvo, Kia, Hyundai, Jaguar, Range Rover and all VW group brands. So the consequences of Audi (and I guess they share the same backend for all VW brands) might be quite significant in terms of customer dissatisfaction and market share loss, if other oems handle sich innovative topics in a more open way.

But as you say, chances are super low and I don't have big hope...

**Comment by jocxfin** [comment]
@slot-tronic did you get a response from Audi? just out of curiosity

**Comment by slot-tronic** [comment]
Hi @jocxfin, 

yes, I got one but only an useless standard answer unfortunately. 

However, since I removed my Audi car from the integration and added it again with a refresh rate of 60 minutes, it seems to work mostly again. Maybe the 10 minutes together with the Tibber PowerUp and the my Audi App (I use a desktop widget on my mobile phone which may also cause more frequent update requests) caused too many requests.

Still sometimes the MyAudi App cannot connect and shows an error message, but not any more the one saying "Too many requests".

But happy to be able to use it again, thanks mich for the great integration!!!

**Comment by gmp91** [comment]
This seems to be a Volkswagen AG problem, not only Audi. 
I manage our companys car fleet with HA and since VW switched from WeConnect app to Volkswagen App they also included the limited call rate and I constantly loose access to the E-UPs. Now I integrated the latest Audi Q8 e-tron with this integration and I hope not to encounter the same problems. It is running for two days now without an error.
So the limited call rate is a global Volkswagen issue

**Comment by jocxfin** [comment]
@slot-tronic thanks for the response!

@gmp91 I actually found one thing which might've caused the issues: for my car the short term and long term trip data are not available for some reason, and the api was giving me 403 responses every 10 mins and multiple ones at once. So i figured what if they're not singling out the ones using 3rd party apps but rather the ones who are getting 403(because I don't believe the myAudi app pings any api which it doesn't have access to).so i modified the code and removed the short term and long term trip data requests and now it's working perfectly with 10min interval. Been running for 5 days now.

**Comment by jocxfin** [comment]
![image](https://github.com/arjenvrh/audi_connect_ha/assets/19174728/1f075187-71b4-4e02-8787-b21eb36eb5ac)

**Comment by gangemij** [comment]
@jocxfin Was that by commenting out the two get_tripdata calls in the audi_connect_account.py code. I have tried the same and am waiting to see if that has done the trick for me also. Thanks for sharing this.

**Comment by jocxfin** [comment]
@gangemij I'll provide the code a bit later as i can't remember right now what were the exact changes.

**Comment by jocxfin** [comment]
[audi_connect_account.txt](https://github.com/arjenvrh/audi_connect_ha/files/13759114/audi_connect_account.txt)

@gangemij there's the whole audi_connect_account.py file. GitHub did not like .py files and i didnt remember what i had changed so there you go with the whole file. Please go through it before deploying it. Although it shouldnt have any issues as it's working perfectly for me, it's always good to double check.

**Comment by woopstar** [comment]
> @gangemij there's the whole audi_connect_account.py file. GitHub did not like .py files and i didnt remember what i had changed so there you go with the whole file. Please go through it before deploying it. Although it shouldnt have any issues as it's working perfectly for me, it's always good to double check.

Here is the diff between the original and yours:

```
$ git diff audi_connect_account.py audi_connect_account.txt 
diff --git a/audi_connect_account.py b/audi_connect_account.txt
index d23bfca..5ff6d02 100644
--- a/audi_connect_account.py
+++ b/audi_connect_account.txt
@@ -402,10 +402,10 @@ class AudiConnectVehicle:
             info = "statusreport"
             await self.call_update(self.update_vehicle_statusreport, 3)
             info = "shortterm"
-            await self.call_update(self.update_vehicle_shortterm, 3)
-            info = "longterm"
-            await self.call_update(self.update_vehicle_longterm, 3)
-            info = "position"
+           # await self.call_update(self.update_vehicle_shortterm, 3)
+           #info = "longterm"
+           # await self.call_update(self.update_vehicle_longterm, 3)
+           #info = "position"
             await self.call_update(self.update_vehicle_position, 3)
             info = "climater"
             await self.call_update(self.update_vehicle_climater, 3)
```

**Comment by jocxfin** [comment]
Thanks @woopstar and Merry Christmas!

**Comment by gangemij** [comment]
Thanks @woopstar and @jocxfin I have made the same changes to my file and will monitor over the next week. If this works we should to make a PR and have the main Repo updated.

**Comment by jocxfin** [comment]
@gangemij i havent had any issues, what about you?

**Comment by gangemij** [comment]
> @gangemij i havent had any issues, what about you?

No mine has been running perfectly since I made the change. I think you have found the issue.

**Comment by Gunth** [comment]
No errors on my side either since i made the change..

**Comment by fhloston** [comment]
I can confirm, that making a similar edit (not commenting out "position" but rather "shortterm") my audi_connect account is no longer blocked when enabling this integration.

**Comment by kgbvax** [comment]
> I get the following bad news (sorry for the German, but this is my UI language):
Hello, IMHO this is not a message hinting for a clamp-down on 3rd party access but rather on a removal of connect functions from the myAudi website. 
That migration has been visibly going on for a while and is in-line with a general trend to go "app only" (see Tibber and others).
