### ISSUE TITLE
Make remaining charge time a datetime?

### ISSUE THREAD

**Issue by wigster** [audiconnect/audi_connect_ha#318]
Would it make sense to make the remaining charge time an estimated datetime set for the latest predicted charge completion time as opposed to the raw number of minutes of charging remaining being reported by the API?

In this way, in the dashboard one could use it as a countdown as opposed to just updating every 10-15 minutes as the charging takes place and HA polls the integration.

**Comment by coreywillwhat** [comment]
This is a good idea. I'll look into it.

**Comment by coreywillwhat** [comment]
I've completed this and tested on my end and its working as expected. Would like input on functionality though.

Currently I'm using the `last_update` datetime as the anchor to calculate the estimated completion datetime, but this means once the `charge_time_remaining` hits 0, the new sensor would always display the time of the last update. Since the vehicle may update frequently or infrequently, once it is at 0 the displayed time wouldn't be very helpful. So i've also added that the sensor will return `None` or unknown if the remaining time is 0.

Let me know if you have a better idea.

**Comment by wigster** [comment]
I guess it would be useful to be able to differentiate between having run to 0 remaining time and expecting to have finished, and not charging at all/not being known. The idea being that, with zero remaining, you can put “was supposed to have finished” as a message on the dashboard. 

So maybe a date time in the past seems ok to me. The sensor could be called something like “expected charge completion time” and if it’s in the past it is not unreasonable. 

For what it’s worth, My hybrid seems to update very often while it’s being charged, and very rarely when just parked.

**Comment by coreywillwhat** [comment]
![image](https://github.com/audiconnect/audi_connect_ha/assets/104224685/df4dd0f2-a3f0-4d92-9791-8ad9b16f420d)
Name: **Charging Complete Time**
- I removed 'expected' from your suggested name as this wouldn't make sense if its in the past.
- Using "Charging" to align with the other sensors.
- I've updated the sensor to display the `datetime` regardless of in the past or not.
Thanks for the idea and input! I'll get a PR put together. There is one dependency PR ahead of this.
