### ISSUE TITLE
Unit of Measurement not applying

### ISSUE THREAD

**Issue by leacho73** [audiconnect/audi_connect_ha#342]
Hi All,

Thanks for the hard work on my other issue: #158 - but I've noticed that I'm not able to change the unit of measurement value as expected - whenever I select a different unit other then KM and click update - nothing happens and the measurement is still in KM.

Any ideas?

Cheers

**Comment by coreywillwhat** [comment]
Good find.
Looks like the value and unit is determined at account setup when you choose the region.
We'll need to look into this.

@Kolbi @cdnninja I think we need to use `native_unit_of_measurement` instead of these conversions?
https://github.com/audiconnect/audi_connect_ha/blob/master/custom_components/audiconnect/dashboard.py#L153-159
https://github.com/audiconnect/audi_connect_ha/blob/master/custom_components/audiconnect/dashboard.py#L172-180

**Comment by cdnninja** [comment]
Yes I think that is correct.  It would let users switch the sensors to other measurements.
