### ISSUE TITLE
Add target soc percent "targetSOC_pct" for e-tron

### ISSUE THREAD

**Issue by epweston** [audiconnect/audi_connect_ha#404]
First, thank you so much for everyone's work on this project.

I would love to be able to  read the target charge value and was hoping "targetSOC_pct" under "chargingSettings" could be added.
Let me know if I did not supply enough information.

Thank you

**Comment by Kolbi** [comment]
Can you please attach a log file? The return value from the API would be enough if you don't want to attach the whole file. Which etron do you own?

**Comment by epweston** [comment]
Yes, and we have the:

Q4 e-tron® Premium 50 e-tron® quattro® (2023)

[home-assistant_audiconnect_2024-04-19T22-01-02.814Z.log](https://github.com/audiconnect/audi_connect_ha/files/15047113/home-assistant_audiconnect_2024-04-19T22-01-02.814Z.log)

Thanks

**Comment by Kolbi** [comment]
Hi added this PR, do you have the possibility to test it?

**Comment by mpredfearn** [comment]
Maybe it would be worth adding this as a "number" entity in case the API that the API uses to change it becomes known?

**Comment by Kolbi** [comment]
> Maybe it would be worth adding this as a "number" entity in case the API that the App uses to change it becomes known?

Sorry I didn't got your point. :) Can you explain it a little bit more?

**Comment by mpredfearn** [comment]
https://github.com/audiconnect/audi_connect_ha/pull/405 adds "target SoC" as a sensor suggesting it is read only. The app is able to update this, it is read write, so a "number" entity would be more appropriate.

**Comment by epweston** [comment]
> Hi added this PR, do you have the possibility to test it?

Sure np, can I just replace certain files in config\custom_components\audiconnect and restart HA, if so, where to I find the file(s)?
Or do I wait for the releases?
Thanks in advance.

**Comment by coreywillwhat** [comment]
The Target SOC sensor should read the current state of the vehicle as provided by the API. Sensors are by nature unchangeable and are just readings from the device/vehicle/API. I haven't tested, but #405 looks like it meets the requirement of a target SOC sensor.

An `input_number` entity would only make sense as a `control`, but then we would need to figure out the service call to set the target SOC and then update that `input_number` based on the API response and As far as I know, at this time, the service call to set the charger/target SOC of the vehicle is not working due to the API changes and I haven't had time to work on it. I also dont have the ability to set the charger (PHEV) which makes it difficult to test.

@mpredfearn are you able to use the audi connect execute vehicle action to start charging/set target SOC currently?

**Comment by mpredfearn** [comment]
@coreywillwhat I was suggesting a "number" entity which can be RW, not an "input_number" which is WO to the user. Perhaps a sensor combined with a service call for updating it is more in line with the rest of this integration, but most other integrations I have use the different entity types to implement this kind of behaviour.

Unfortunately I am unable to test - my e-tron 55 is a 2019 model before Audi implemented the remote setting of the target charge limit - mine is adjustable from the MMI only :-/

**Comment by Kolbi** [comment]
@mpredfearn as long as we do not have an API to test & set the Target SOC - I would say implement it as RO for the moment.

I openend a new "issue" for implementing Number: https://github.com/audiconnect/audi_connect_ha/issues/412

**Comment by epweston** [comment]
Just applied the 1.7.0 update today and it is working great!
Thanks you!
