### ISSUE TITLE
States not correct or updating

### ISSUE THREAD

**Issue by Jack123uk** [audiconnect/audi_connect_ha#87]
Hey, hope someone can help me out, to what I am doing wrong if anything.
I have a brand new 2021 RS5 I have managed to add my credentials into the Audi connect integration successfully. Home assistant is showing 23 entities, all good so far! I haven’t tried the lock and unlock feature yet! My main issue is the states not showing correctly. No matter what I do it’s always showing my car as unlocked, and the windows are open. 
has anyone had this issue? Or can anyone help with a solution? 
Thanks

**Comment by Jack123uk** [comment]
Anyone 😔🙏

**Comment by lbr-6pac** [comment]
Same issue here

**Comment by siaub** [comment]
Similiar issue with my 2019 A1, everything works flawless, except for the trunk and trunk lock state. They always show open/unlocked when I am locking the car with the keys but when I lock it through the myAudi app it updates correctly (it also updates to open correctly when I unlock the car with the key, only locking does not work properly). Status in the myAudi app is always on point

**Comment by danantonson** [comment]
Same issue here with the 2019 A1. It doesn't look like any of the states update.

**Comment by Rookie-Ron** [comment]
Same issue here with 2017 A5 Coupe 2.0 TSFI quattro Sport.
Also refer to Issue #55, I have exactly the same behavior. The only way I can confirm my car is 'locked', is by the '_trunk-lock' entity.
My Audi App represents the correct status when I open/ close doors, windows etc.:

<img width="408" alt="image" src="https://user-images.githubusercontent.com/77362566/148595883-91bb64d0-a357-473d-8cc1-21be19494470.png">

<img width="556" alt="image" src="https://user-images.githubusercontent.com/77362566/148595987-a116e773-d058-49ff-89fa-1bdae0f9236f.png">

@arjenvrh Any developments, comments on this issue?

**Comment by Jean-Jerrre** [comment]
Hey  guys, I figured out what issue was some time ago. But don't anything about programming. The only things I know Is what I learned myself in the past year.

The thing is:
We all choose that beautiful coupé.... Audi knows it has only 2 doors., only audi_conect_ha is not aware yet. Because I thought would say stupid things on here. I didn't dare to post here before.

So if you go to audi_models.py you can see there are all th states for cars with front and rear doors listed
![Door states](https://user-images.githubusercontent.com/72252694/151472500-94d0fa27-b366-44d8-8f8e-4f73843c26fd.png)

And if you go to audi_connect_account.py you can clearly see they still use the rear doors to define if all doors are locked or not. Since there are no fysical rear doors, it is certainly not possible to be locked. And thats why audi_connect_ha keeps returning that not all doors are locked (so unlocked).

![any_door_state](https://user-images.githubusercontent.com/72252694/151472516-fa25d418-d1fd-47b6-abdc-02407b8075f4.PNG)

Because I didn't want to get involved in difficult programming. I just changed the rear doors into front doors again...  You can see that in the picture where I already changed them. So audi_connect_ha still thinks i'm drivig a sportback. But it is actuallly just checking the state of the front doors twice for me know....

But I am sure you guys will find a decent way to solve it.... 


Grtz
Jeroen


.

**Comment by Jean-Jerrre** [comment]
> Hey, hope someone can help me out, to what I am doing wrong if anything. I have a brand new 2021 RS5 I have managed to add my credentials into the Audi connect integration successfully. Home assistant is showing 23 entities, all good so far! I haven’t tried the lock and unlock feature yet! My main issue is the states not showing correctly. No matter what I do it’s always showing my car as unlocked, and the windows are open. has anyone had this issue? Or can anyone help with a solution? Thanks

Btw, if I was helpful to you, take me for a ride in your RS5... Even if you let me just stare at it for a few minutes, I'll be satisfied.

**Comment by coreywillwhat** [comment]
This appears to be fixed about 6 months ago and issue has been stale for almost 2 years.
Closing but please report an issue if you have one.
